import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

// import React from 'react';
// import { AntdRegistry } from '@ant-design/nextjs-registry';

// const RootLayout = ({ children }) => (
//   <html lang="en">
//     <body>
//       <AntdRegistry>{children}</AntdRegistry>
//     </body>
//   </html>
// );

// export default RootLayout;